# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: keycloak-demo

steps:
  - task: Docker@2
    displayName: 'Logga in i ACR'
    inputs:
      command: login
      containerRegistry: 'rg-assa-dev-conn'

  - task: Docker@2
    displayName: 'Bygg Docker-bild'
    inputs:
      command: build
      Dockerfile: '**/Dockerfile'
      tags: |
        $(imageName):$(Build.BuildId)

  - task: Docker@2
    displayName: 'Push till ACR'
    inputs:
      command: push
      tags: |
        $(imageName):$(Build.BuildId)
